# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_month', models.CharField(max_length=8)),
                ('event_day', models.SmallIntegerField()),
                ('event_description', models.TextField()),
                ('event_type', models.CharField(max_length=300)),
            ],
        ),
    ]
