# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.CharField(default='twitter.com', max_length=500),
            preserve_default=False,
        ),
    ]
