# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20171222_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_month', models.CharField(max_length=8)),
                ('build_year', models.IntegerField()),
                ('build_event_count', models.IntegerField()),
            ],
        ),
    ]
